// "use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "AIVSS",
//   description: "Generated by create next app",
// };
// import { useState, useEffect, useRef, ReactNode } from "react";
// import Link from "next/link";
// import { usePathname } from "next/navigation";
// import {
//   Activity,
//   Search,
//   Eye,
//   Triangle,
//   Wrench,
//   FileText,
//   ChevronDown,
//   Folder,
//   Link as LinkIcon,
//   Database,
//   Unlock,
//   CheckCircle,
// } from "lucide-react";

// // NOTE: We fetch latestScanTime in the page component and pass it up if needed,
// // or ideally, create a dedicated client component for the header.
// // For simplicity, we'll keep it static here for now.
// interface NavigationItem {
//   name: string;
//   href: string;
//   icon: any;
//   tag?: string;
// }

// export default function RootLayout({ children }: { children: ReactNode }) {
//   const [isProjectsDropdownOpen, setIsProjectsDropdownOpen] = useState(false);
//   const [selectedProject, setSelectedProject] = useState("Multi Agent System");
//   const pathname = usePathname();
//   const dropdownRef = useRef<HTMLDivElement>(null);

//   useEffect(() => {
//     const handleClickOutside = (event: MouseEvent) => {
//       if (
//         dropdownRef.current &&
//         !dropdownRef.current.contains(event.target as Node)
//       ) {
//         setIsProjectsDropdownOpen(false);
//       }
//     };

//     document.addEventListener("mousedown", handleClickOutside);
//     return () => {
//       document.removeEventListener("mousedown", handleClickOutside);
//     };
//   }, []);

//   const navigation = [
//     {
//       section: "Overview Analysis",
//       items: [
//         { name: "Dashboard", href: "/", icon: Activity },
//         { name: "System Schema", href: "/system-schema", icon: LinkIcon },
//         {
//           name: "Vulnerability Scan",
//           href: "/vulnerability-scan",
//           icon: Search,
//         },
//         { name: "Attack Monitoring", href: "/attack-monitoring", icon: Eye },
//         {
//           name: "Threat Intelligence",
//           href: "/threat-intelligence",
//           icon: Triangle,
//         },
//       ] as NavigationItem[],
//     },
//     {
//       section: "Attack Vectors",
//       items: [
//         {
//           name: "Data Poisoning",
//           href: "/data-poisoning",
//           icon: Database,
//           tag: "Medium",
//         },
//         {
//           name: "Jailbreaks",
//           href: "/jailbreaks",
//           icon: Unlock,
//           tag: "Critical",
//         },
//       ] as NavigationItem[],
//     },
//     {
//       section: "Security & Monitoring",
//       items: [
//         { name: "Hardening Tools", href: "/hardening-tools", icon: Wrench },
//         {
//           name: "Prompt Hardening",
//           href: "/prompt-hardening",
//           icon: CheckCircle,
//         },
//         { name: "Risk Reports", href: "/risk-reports", icon: FileText },
//         { name: "System Monitor", href: "/system-monitor", icon: Activity },
//       ] as NavigationItem[],
//     },
//   ];

//   const projects = [
//     {
//       id: "multi-agent-system",
//       name: "Multi Agent System",
//       description: "Comprehensive multi-agent security scanner",
//     },
//   ];

//   return (
//     <html lang="en">
//       <body>
//         <div className="min-h-screen">
//           <div className="flex h-screen bg-background">
//             {/* Sidebar */}
//             <div className="w-64 bg-sidebar border-r border-sidebar-border flex flex-col">
//               <div className="p-4 border-b border-sidebar-border">
//                 <div>
//                   <h1 className="text-lg font-bold text-sidebar-foreground">
//                     aegent/dev
//                   </h1>
//                   <p className="text-xs text-sidebar-foreground">
//                     Agentic Security Scanner
//                   </p>
//                   <p className="text-xs text-muted-foreground mt-2">
//                     This is a proof of concept of our multi agent security
//                     scanner. We love ideas and recommendations of what you'd
//                     like to see in such a tool!
//                     <a
//                       href="https://www.aegentdev.com/contact"
//                       target="_blank"
//                       rel="noopener noreferrer"
//                       className="text-blue-600 underline"
//                     >
//                       {" "}
//                       Click here to contact us!
//                     </a>
//                   </p>
//                 </div>
//               </div>

//               <nav className="flex-1 p-4 space-y-6 overflow-y-auto">
//                 {navigation.map((section) => (
//                   <div key={section.section}>
//                     <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
//                       {section.section}
//                     </h3>
//                     <ul className="space-y-1">
//                       {section.items.map((item) => {
//                         const Icon = item.icon;
//                         const isActive = pathname === item.href;
//                         return (
//                           <li key={item.name}>
//                             <Link
//                               href={item.href}
//                               className={`flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors ${
//                                 isActive
//                                   ? "bg-sidebar-accent text-sidebar-accent-foreground"
//                                   : "text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
//                               }`}
//                             >
//                               <Icon size={18} className="mr-3" />
//                               <span className="flex-1">{item.name}</span>
//                               {item.tag && (
//                                 <span
//                                   className={`px-2 py-1 text-xs rounded-full ${
//                                     item.tag === "Critical"
//                                       ? "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200"
//                                       : "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200"
//                                   }`}
//                                 >
//                                   {item.tag}
//                                 </span>
//                               )}
//                             </Link>
//                           </li>
//                         );
//                       })}
//                     </ul>
//                   </div>
//                 ))}
//               </nav>

//               <div className="p-4 border-t border-sidebar-border">
//                 <div>
//                   <p className="text-xs text-muted-foreground">
//                     <a
//                       href="https://www.aegentdev.com/blog"
//                       target="_blank"
//                       rel="noopener noreferrer"
//                       className="text-blue-600 underline hover:text-blue-800"
//                     >
//                       Click here to check out our research and blogs!
//                     </a>
//                   </p>
//                 </div>
//               </div>
//             </div>

//             {/* Main content */}
//             <div className="flex-1 flex flex-col overflow-hidden">
//               <header className="bg-card border-b border-border px-6 py-4">
//                 <div className="flex items-center justify-between">
//                   {/* Header content from original AppLayout.tsx */}
//                   {/* NOTE: We'll make latestScanTime dynamic inside the page itself */}
//                 </div>
//               </header>

//               <main className="flex-1 overflow-auto">{children}</main>
//             </div>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";

import "./globals.css";
import AppShell from "@/components/AppShell"; // <-- Import our new Client Component

// This is a Server Component, so we can export metadata
export const metadata: Metadata = {
  title: "AIVSS - Agentic Security Scanner",
  description: "A platform for securing multi-agent systems.",
};

// This is a Server Component, it has no hooks or state
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
